#!/bin/sh
# The colours of the buttons (PEBBLES=a colour from the wallpaper and GEMS=icons theme colour)
PEBBLES="#EAD57C"
GRADIENT_PEBBLES="#F3F2E0"
GEMS="#e8a040"
GRADIENT_GEMS="yellow"
convert closefcs_original.xpm -fill $PEBBLES -opaque "#fffff0" tmp.png
mogrify -region '4x1+4+11' -fill $GRADIENT_PEBBLES -colorize 3% tmp.png
mogrify -region '4x1+4+10' -fill $GRADIENT_PEBBLES -colorize 6% tmp.png
mogrify -region '4x1+4+9' -fill $GRADIENT_PEBBLES -colorize 9% tmp.png
mogrify -region '2x1+1+8' -fill $GRADIENT_PEBBLES -colorize 12% tmp.png
mogrify -region '2x1+5+8' -fill $GRADIENT_PEBBLES -colorize 12% tmp.png
mogrify -region '2x1+9+8' -fill $GRADIENT_PEBBLES -colorize 12% tmp.png
mogrify -region '4x1+0+7' -fill $GRADIENT_PEBBLES -colorize 15% tmp.png
mogrify -region '4x1+8+7' -fill $GRADIENT_PEBBLES -colorize 15% tmp.png
mogrify -region '4x1+0+6' -fill $GRADIENT_PEBBLES -colorize 18% tmp.png
mogrify -region '4x1+8+6' -fill $GRADIENT_PEBBLES -colorize 18% tmp.png
mogrify -region '4x1+0+5' -fill $GRADIENT_PEBBLES -colorize 21% tmp.png
mogrify -region '4x1+8+5' -fill $GRADIENT_PEBBLES -colorize 21% tmp.png
mogrify -region '2x1+1+4' -fill $GRADIENT_PEBBLES -colorize 24% tmp.png
mogrify -region '2x1+5+4' -fill $GRADIENT_PEBBLES -colorize 24% tmp.png
mogrify -region '2x1+9+4' -fill $GRADIENT_PEBBLES -colorize 24% tmp.png
mogrify -region '4x1+4+3' -fill $GRADIENT_PEBBLES -colorize 27% tmp.png
mogrify -region '4x1+4+2' -fill $GRADIENT_PEBBLES -colorize 30% tmp.png
mogrify -region '4x1+4+1' -fill $GRADIENT_PEBBLES -colorize 33% tmp.png
mogrify -region '2x1+5+0' -fill $GRADIENT_PEBBLES -colorize 35% tmp.png
convert tmp.png closefcs_custom.xpm
# Close button finished
convert maxfcs_original.xpm -fill $GEMS -opaque "#fffff0" tmp.png
mogrify -region '4x1+2+6' -fill $GRADIENT_GEMS -colorize 5% tmp.png
mogrify -region '6x1+1+5' -fill $GRADIENT_GEMS -colorize 10% tmp.png
mogrify -region '8x1+0+4' -fill $GRADIENT_GEMS -colorize 15% tmp.png
mogrify -region '8x1+0+3' -fill $GRADIENT_GEMS -colorize 20% tmp.png
mogrify -region '6x1+1+2' -fill $GRADIENT_GEMS -colorize 25% tmp.png
mogrify -region '4x1+2+1' -fill $GRADIENT_GEMS -colorize 30% tmp.png
mogrify -region '2x1+3+0' -fill $GRADIENT_GEMS -colorize 35% tmp.png
convert tmp.png maxfcs_custom.xpm
# Maximize button finished
convert shadefcs_original.xpm -fill $GEMS -opaque "#fffff0" tmp.png
mogrify -region '6x1+1+6' -fill $GRADIENT_GEMS -colorize 10% tmp.png
mogrify -region '8x1+0+5' -fill $GRADIENT_GEMS -colorize 15% tmp.png
mogrify -region '8x1+0+4' -fill $GRADIENT_GEMS -colorize 20% tmp.png
mogrify -region '6x1+1+3' -fill $GRADIENT_GEMS -colorize 25% tmp.png
mogrify -region '4x1+2+2' -fill $GRADIENT_GEMS -colorize 30% tmp.png
mogrify -region '2x1+3+1' -fill $GRADIENT_GEMS -colorize 35% tmp.png
convert tmp.png shadefcs_custom.xpm
# Shade button finished
convert unshadefcs_original.xpm -fill $GEMS -opaque "#fffff0" tmp.png
mogrify -region '4x1+2+5' -fill $GRADIENT_GEMS -colorize 5% tmp.png
mogrify -region '6x1+1+4' -fill $GRADIENT_GEMS -colorize 10% tmp.png
mogrify -region '8x1+0+3' -fill $GRADIENT_GEMS -colorize 15% tmp.png
mogrify -region '8x1+0+2' -fill $GRADIENT_GEMS -colorize 20% tmp.png
mogrify -region '6x1+1+1' -fill $GRADIENT_GEMS -colorize 25% tmp.png
convert tmp.png unshadefcs_custom.xpm
# Unshade button finished
rm tmp.png
echo Done. Everything ok.
exit


